### ISSUE TITLE
Task management platform

### ISSUE THREAD

**Issue by zebleck** [IntegrierBar/FPComputerGames#1]
Spätestens ab Start sollten wir eine Task Management software benutzen. Sehe in der Dokumentation oft Trello (https://trello.com/de), aber würde auch gerne mal das neue Feature GitHub Projects in Action sehen, was im Prinzip ein Konkurrent zu Trello ist. Vorteil wäre, dass wir fast alles in GitHub zentralisiert hätten.

https://docs.github.com/de/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects

thoughts?

**Comment by zebleck** [comment]
wobei Prof. Hesser hat im Dokument geschrieben er will in trello auch karten kommentieren also ist trello vielleicht besser

**Comment by IntegrierBar** [comment]
Ja, wahrscheinlich sollten wir es dann erstmal auf Trello machen.

**Comment by zebleck** [comment]
https://trello.com/b/iLUiTVXe/fp-computer-games
