### ISSUE TITLE
C# or C++ (Web export issue)

### ISSUE THREAD

**Issue by zebleck** [IntegrierBar/FPComputerGames#2]
It seems Godot 4.2 doesn't support web export for games programmed with C#. 

A decision has to be made whether to switch to C++ or switch to an older version of Godot that supports C# web export.

Best to ask Prof. Dr. Hesser if web export is truly necessary, as without it, we could continue using C# and the latest Godot version.

**Comment by IntegrierBar** [comment]
We do not need a web export. We only need to present the project in an online meeting
